name = "ModelMiner"
uuid = "93a108e7-a327-4478-9a72-b0f8ee6311f8"
authors = ["Vishnu Raj"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
